### PR TITLE
issue/29 - Bump WordPress minimum requirements

### PR DESCRIPTION
**Pull request by dbeja**
Issue #29

**Housekeeping**

* [x] Issue number has been linked below the description
* [x] Branch name follows the `issue/###` or `release/###` format
* [x] PR title is prefixed with the branch name (issue/### - Title)

**Proposed changes**

* [x] Code has been tested with no errors
* [x] Code meets stated minimum requirements
* [x] Code should (usually) not contain unrelated changes
* [x] Code style (including docs) and organization is generally consistent with the rest of the codebase
* [x] Before and after screenshots have been posted to document visual changes
* [x] Clear steps for testing the PR have been posted (as needed)

## How to test it
1. Install and activate AffiliateWP Leaderboard add-on
2. Confirm the plugin works as expected without any PHP errors.
3. Create a new page with the shortcode `[affiliate_leaderboard]` and confirm the page shows the leaderboard

### CODE REVIEW

**Review by DrewAPicture — APPROVED** [review]
Changes looks good. Tested and looks good.

**Review by DrewAPicture — CHANGES_REQUESTED** [review]
Actually, I just realized that as this is a free add-on, we need to update the "Requires at least" header in the readme.txt to 5.2 and update the changelog.

**Comment by dbeja** [comment]
> Actually, I just realized that as this is a free add-on, we need to update the "Requires at least" header in the readme.txt to 5.2 and update the changelog.

@DrewAPicture shouldn't that be updated only on the release PR?

**Review by DrewAPicture — APPROVED** [review]
Looks good.

**Pull request merged**
